=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ConfigChangeRequestStatus
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL".freeze
    APPROVED = "APPROVED".freeze
    CANCELLED = "CANCELLED".freeze
    REJECTED = "REJECTED".freeze
    FAILED = "FAILED".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ConfigChangeRequestStatus.constants.select { |c| ConfigChangeRequestStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ConfigChangeRequestStatus" if constantValues.empty?
      value
    end
  end
end
