=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ExchangeType
    BITTREX = "BITTREX".freeze
    COINBASEPRO = "COINBASEPRO".freeze
    BINANCE = "BINANCE".freeze
    BINANCEUS = "BINANCEUS".freeze
    BITMEX = "BITMEX".freeze
    KRAKEN = "KRAKEN".freeze
    GEMINI = "GEMINI".freeze
    BITFINEX = "BITFINEX".freeze
    BITSTAMP = "BITSTAMP".freeze
    POLONIEX = "POLONIEX".freeze
    DERIBIT = "DERIBIT".freeze
    LIQUID = "LIQUID".freeze
    HUOBI = "HUOBI".freeze
    BITHUMB = "BITHUMB".freeze
    OKEX = "OKEX".freeze
    OKCOIN = "OKCOIN".freeze
    HITBTC = "HITBTC".freeze
    KORBIT = "KORBIT".freeze
    SEEDCX = "SEEDCX".freeze
    BITSO = "BITSO".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ExchangeType.constants.select { |c| ExchangeType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ExchangeType" if constantValues.empty?
      value
    end
  end
end
