=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TradingAccountType
    FUNDABLE = "FUNDABLE".freeze
    SPOT = "SPOT".freeze
    FUNDING = "FUNDING".freeze
    FUTURES = "FUTURES".freeze
    OPTIONS = "OPTIONS".freeze
    MARGIN = "MARGIN".freeze
    MARGIN_CROSS = "MARGIN_CROSS".freeze
    MARGIN_ISOLATED = "MARGIN_ISOLATED".freeze
    EXCHANGE = "EXCHANGE".freeze
    COIN_MARGINED_SWAP = "COIN_MARGINED_SWAP".freeze
    USDT_MARGINED_SWAP_CROSS = "USDT_MARGINED_SWAP_CROSS".freeze
    USDT_MARGINED_SWAP_ISOLATED = "USDT_MARGINED_SWAP_ISOLATED".freeze
    USDT_FUTURES = "USDT_FUTURES".freeze
    COIN_FUTURES = "COIN_FUTURES".freeze
    FUTURES_CROSS = "FUTURES_CROSS".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TradingAccountType.constants.select { |c| TradingAccountType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TradingAccountType" if constantValues.empty?
      value
    end
  end
end
