=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TransactionSubStatus
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS".freeze
    AMOUNT_TOO_SMALL = "AMOUNT_TOO_SMALL".freeze
    UNSUPPORTED_ASSET = "UNSUPPORTED_ASSET".freeze
    UNAUTHORISED__MISSING_PERMISSION = "UNAUTHORISED__MISSING_PERMISSION".freeze
    INVALID_SIGNATURE = "INVALID_SIGNATURE".freeze
    API_INVALID_SIGNATURE = "API_INVALID_SIGNATURE".freeze
    UNAUTHORISED__MISSING_CREDENTIALS = "UNAUTHORISED__MISSING_CREDENTIALS".freeze
    UNAUTHORISED__USER = "UNAUTHORISED__USER".freeze
    UNAUTHORISED__DEVICE = "UNAUTHORISED__DEVICE".freeze
    INVALID_UNMANAGED_WALLET = "INVALID_UNMANAGED_WALLET".freeze
    INVALID_EXCHANGE_ACCOUNT = "INVALID_EXCHANGE_ACCOUNT".freeze
    INSUFFICIENT_FUNDS_FOR_FEE = "INSUFFICIENT_FUNDS_FOR_FEE".freeze
    INVALID_ADDRESS = "INVALID_ADDRESS".freeze
    WITHDRAW_LIMIT = "WITHDRAW_LIMIT".freeze
    API_CALL_LIMIT = "API_CALL_LIMIT".freeze
    ADDRESS_NOT_WHITELISTED = "ADDRESS_NOT_WHITELISTED".freeze
    TIMEOUT = "TIMEOUT".freeze
    CONNECTIVITY_ERROR = "CONNECTIVITY_ERROR".freeze
    THIRD_PARTY_INTERNAL_ERROR = "THIRD_PARTY_INTERNAL_ERROR".freeze
    CANCELLED_EXTERNALLY = "CANCELLED_EXTERNALLY".freeze
    INVALID_THIRD_PARTY_RESPONSE = "INVALID_THIRD_PARTY_RESPONSE".freeze
    VAULT_WALLET_NOT_READY = "VAULT_WALLET_NOT_READY".freeze
    MISSING_DEPOSIT_ADDRESS = "MISSING_DEPOSIT_ADDRESS".freeze
    INTERNAL_ERROR = "INTERNAL_ERROR".freeze
    UNKNOWN_ERROR = "UNKNOWN_ERROR".freeze
    AUTHORIZER_NOT_FOUND = "AUTHORIZER_NOT_FOUND".freeze
    INSUFFICIENT_RESERVED_FUNDING = "INSUFFICIENT_RESERVED_FUNDING".freeze
    MANUAL_DEPOSIT_ADDRESS_REQUIRED = "MANUAL_DEPOSIT_ADDRESS_REQUIRED".freeze
    INVALID_FEE = "INVALID_FEE".freeze
    ERROR_UNSUPPORTED_TRANSACTION_TYPE = "ERROR_UNSUPPORTED_TRANSACTION_TYPE".freeze
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION".freeze
    N3_RD_PARTY_PROCESSING = "3RD_PARTY_PROCESSING".freeze
    PENDING_BLOCKCHAIN_CONFIRMATIONS = "PENDING_BLOCKCHAIN_CONFIRMATIONS".freeze
    N3_RD_PARTY_CONFIRMING = "3RD_PARTY_CONFIRMING".freeze
    CONFIRMED = "CONFIRMED".freeze
    N3_RD_PARTY_COMPLETED = "3RD_PARTY_COMPLETED".freeze
    PENDING_BLOCKCHAIN_CONFIRMATIONSREJECTED_BY_USER = "PENDING_BLOCKCHAIN_CONFIRMATIONSREJECTED_BY_USER".freeze
    CANCELLED_BY_USER = "CANCELLED_BY_USER".freeze
    N3_RD_PARTY_CANCELLED = "3RD_PARTY_CANCELLED".freeze
    N3_RD_PARTY_REJECTED = "3RD_PARTY_REJECTED".freeze
    AML_SCREENING_REJECTED = "AML_SCREENING_REJECTED".freeze
    BLOCKED_BY_POLICY = "BLOCKED_BY_POLICY".freeze
    FAILED_AML_SCREENING = "FAILED_AML_SCREENING".freeze
    PARTIALLY_FAILED = "PARTIALLY_FAILED".freeze
    N3_RD_PARTY_FAILED = "3RD_PARTY_FAILED".freeze
    ZERO_BALANCE_IN_PERMANENT_ADDRESS = "ZERO_BALANCE_IN_PERMANENT_ADDRESS".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TransactionSubStatus.constants.select { |c| TransactionSubStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TransactionSubStatus" if constantValues.empty?
      value
    end
  end
end
