=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TransactionOperation
    TRANSFER = "TRANSFER".freeze
    MINT = "MINT".freeze
    BURN = "BURN".freeze
    SUPPLY_TO_COMPOUND = "SUPPLY_TO_COMPOUND".freeze
    REDEEM_FROM_COMPOUND = "REDEEM_FROM_COMPOUND".freeze
    RAW = "RAW".freeze
    CONTRACT_CALL = "CONTRACT_CALL".freeze
    INTERNAL_LEDGER_TRANSFER = "INTERNAL_LEDGER_TRANSFER".freeze
    TYPED_MESSAGE = "TYPED_MESSAGE".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TransactionOperation.constants.select { |c| TransactionOperation::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TransactionOperation" if constantValues.empty?
      value
    end
  end
end
