=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class VaultAsset
    attr_accessor :id

    # The total wallet balance. In EOS this value includes the network balance, self staking and pending refund. For all other coins it is the balance as it appears on the blockchain.
    attr_accessor :total

    # Deprecated - replaced by \"total\"
    attr_accessor :balance

    # Funds available for transfer. Equals the blockchain balance minus any locked amounts
    attr_accessor :available

    # The cumulative balance of all transactions pending to be cleared
    attr_accessor :pending

    # The cumulative frozen balance
    attr_accessor :frozen

    # Funds in outgoing transactions that are not yet published to the network
    attr_accessor :locked_amount

    # Staked balance
    attr_accessor :staked

    attr_accessor :total_staked_cpu

    attr_accessor :total_staked_network

    attr_accessor :self_staked_cpu

    attr_accessor :self_staked_network

    attr_accessor :pending_refund_cpu

    attr_accessor :pending_refund_network

    attr_accessor :block_height

    attr_accessor :block_hash

    attr_accessor :allocated_balances

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'total' => :'total',
        :'balance' => :'balance',
        :'available' => :'available',
        :'pending' => :'pending',
        :'frozen' => :'frozen',
        :'locked_amount' => :'lockedAmount',
        :'staked' => :'staked',
        :'total_staked_cpu' => :'totalStakedCPU',
        :'total_staked_network' => :'totalStakedNetwork',
        :'self_staked_cpu' => :'selfStakedCPU',
        :'self_staked_network' => :'selfStakedNetwork',
        :'pending_refund_cpu' => :'pendingRefundCPU',
        :'pending_refund_network' => :'pendingRefundNetwork',
        :'block_height' => :'blockHeight',
        :'block_hash' => :'blockHash',
        :'allocated_balances' => :'allocatedBalances'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'total' => :'String',
        :'balance' => :'String',
        :'available' => :'String',
        :'pending' => :'String',
        :'frozen' => :'String',
        :'locked_amount' => :'String',
        :'staked' => :'String',
        :'total_staked_cpu' => :'String',
        :'total_staked_network' => :'String',
        :'self_staked_cpu' => :'String',
        :'self_staked_network' => :'String',
        :'pending_refund_cpu' => :'String',
        :'pending_refund_network' => :'String',
        :'block_height' => :'String',
        :'block_hash' => :'String',
        :'allocated_balances' => :'Array<AllocatedBalance>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::VaultAsset` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::VaultAsset`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      end

      if attributes.key?(:'balance')
        self.balance = attributes[:'balance']
      end

      if attributes.key?(:'available')
        self.available = attributes[:'available']
      end

      if attributes.key?(:'pending')
        self.pending = attributes[:'pending']
      end

      if attributes.key?(:'frozen')
        self.frozen = attributes[:'frozen']
      end

      if attributes.key?(:'locked_amount')
        self.locked_amount = attributes[:'locked_amount']
      end

      if attributes.key?(:'staked')
        self.staked = attributes[:'staked']
      end

      if attributes.key?(:'total_staked_cpu')
        self.total_staked_cpu = attributes[:'total_staked_cpu']
      end

      if attributes.key?(:'total_staked_network')
        self.total_staked_network = attributes[:'total_staked_network']
      end

      if attributes.key?(:'self_staked_cpu')
        self.self_staked_cpu = attributes[:'self_staked_cpu']
      end

      if attributes.key?(:'self_staked_network')
        self.self_staked_network = attributes[:'self_staked_network']
      end

      if attributes.key?(:'pending_refund_cpu')
        self.pending_refund_cpu = attributes[:'pending_refund_cpu']
      end

      if attributes.key?(:'pending_refund_network')
        self.pending_refund_network = attributes[:'pending_refund_network']
      end

      if attributes.key?(:'block_height')
        self.block_height = attributes[:'block_height']
      end

      if attributes.key?(:'block_hash')
        self.block_hash = attributes[:'block_hash']
      end

      if attributes.key?(:'allocated_balances')
        if (value = attributes[:'allocated_balances']).is_a?(Array)
          self.allocated_balances = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          total == o.total &&
          balance == o.balance &&
          available == o.available &&
          pending == o.pending &&
          frozen == o.frozen &&
          locked_amount == o.locked_amount &&
          staked == o.staked &&
          total_staked_cpu == o.total_staked_cpu &&
          total_staked_network == o.total_staked_network &&
          self_staked_cpu == o.self_staked_cpu &&
          self_staked_network == o.self_staked_network &&
          pending_refund_cpu == o.pending_refund_cpu &&
          pending_refund_network == o.pending_refund_network &&
          block_height == o.block_height &&
          block_hash == o.block_hash &&
          allocated_balances == o.allocated_balances
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, total, balance, available, pending, frozen, locked_amount, staked, total_staked_cpu, total_staked_network, self_staked_cpu, self_staked_network, pending_refund_cpu, pending_refund_network, block_height, block_hash, allocated_balances].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
