=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::AuthorizationGroups
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::AuthorizationGroups do
  let(:instance) { OpenapiClient::AuthorizationGroups.new }

  describe 'test an instance of AuthorizationGroups' do
    it 'should create an instance of AuthorizationGroups' do
      expect(instance).to be_instance_of(OpenapiClient::AuthorizationGroups)
    end
  end
  describe 'test attribute "th"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "users"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Hash<String, String>', ["PENDING_AUTHORIZATION", "APPROVED", "REJECTED", "NA"])
      # validator.allowable_values.each do |value|
      #   expect { instance.users = value }.not_to raise_error
      # end
    end
  end

end
