=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::FiatAccountType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::FiatAccountType do
  let(:instance) { OpenapiClient::FiatAccountType.new }

  describe 'test an instance of FiatAccountType' do
    it 'should create an instance of FiatAccountType' do
      expect(instance).to be_instance_of(OpenapiClient::FiatAccountType)
    end
  end
end
