=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TradingAccountType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TradingAccountType do
  let(:instance) { OpenapiClient::TradingAccountType.new }

  describe 'test an instance of TradingAccountType' do
    it 'should create an instance of TradingAccountType' do
      expect(instance).to be_instance_of(OpenapiClient::TradingAccountType)
    end
  end
end
