=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TransactionSubStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TransactionSubStatus do
  let(:instance) { OpenapiClient::TransactionSubStatus.new }

  describe 'test an instance of TransactionSubStatus' do
    it 'should create an instance of TransactionSubStatus' do
      expect(instance).to be_instance_of(OpenapiClient::TransactionSubStatus)
    end
  end
end
