=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TransferPeerPathResponseAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TransferPeerPathResponseAllOf do
  let(:instance) { OpenapiClient::TransferPeerPathResponseAllOf.new }

  describe 'test an instance of TransferPeerPathResponseAllOf' do
    it 'should create an instance of TransferPeerPathResponseAllOf' do
      expect(instance).to be_instance_of(OpenapiClient::TransferPeerPathResponseAllOf)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sub_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "virtual_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["OFF_EXCHANGE", "DEFAULT", "UNKNOWN"])
      # validator.allowable_values.each do |value|
      #   expect { instance.virtual_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "virtual_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
