=begin
#Fireblocks API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.5.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/allocate_funds_request'
require 'openapi_client/models/allocated_balance'
require 'openapi_client/models/aml_screening_result'
require 'openapi_client/models/amount_info'
require 'openapi_client/models/asset_type_response'
require 'openapi_client/models/authorization_groups'
require 'openapi_client/models/authorization_info'
require 'openapi_client/models/block_info'
require 'openapi_client/models/cancel_transaction_response'
require 'openapi_client/models/channel'
require 'openapi_client/models/config_change_request_status'
require 'openapi_client/models/create_address_response'
require 'openapi_client/models/create_transaction_response'
require 'openapi_client/models/create_transfer_ticket_response'
require 'openapi_client/models/create_vault_asset_response'
require 'openapi_client/models/deallocate_funds_request'
require 'openapi_client/models/destination_transfer_peer_path'
require 'openapi_client/models/destination_transfer_peer_path_all_of'
require 'openapi_client/models/drop_transaction_request'
require 'openapi_client/models/drop_transaction_response'
require 'openapi_client/models/error'
require 'openapi_client/models/estimated_network_fee_response'
require 'openapi_client/models/estimated_transaction_fee_response'
require 'openapi_client/models/exchange_account'
require 'openapi_client/models/exchange_asset'
require 'openapi_client/models/exchange_trading_account'
require 'openapi_client/models/exchange_type'
require 'openapi_client/models/external_wallet_asset'
require 'openapi_client/models/fee_info'
require 'openapi_client/models/fiat_account'
require 'openapi_client/models/fiat_account_type'
require 'openapi_client/models/fiat_asset'
require 'openapi_client/models/freeze_transaction_response'
require 'openapi_client/models/gas_station_configuration'
require 'openapi_client/models/gas_station_properties_response'
require 'openapi_client/models/get_users_response'
require 'openapi_client/models/network_connection_response'
require 'openapi_client/models/network_fee'
require 'openapi_client/models/network_record'
require 'openapi_client/models/off_exchange_entity_response'
require 'openapi_client/models/off_exchange_entity_response_balance'
require 'openapi_client/models/one_time_address'
require 'openapi_client/models/public_key_information'
require 'openapi_client/models/resend_webhooks_response'
require 'openapi_client/models/set_confirmations_threshold_request'
require 'openapi_client/models/set_confirmations_threshold_response'
require 'openapi_client/models/signed_message'
require 'openapi_client/models/signed_message_signature'
require 'openapi_client/models/term'
require 'openapi_client/models/trading_account_type'
require 'openapi_client/models/transaction_fee'
require 'openapi_client/models/transaction_operation'
require 'openapi_client/models/transaction_request'
require 'openapi_client/models/transaction_request_destination'
require 'openapi_client/models/transaction_response'
require 'openapi_client/models/transaction_response_destination'
require 'openapi_client/models/transaction_sub_status'
require 'openapi_client/models/transfer_peer_path'
require 'openapi_client/models/transfer_peer_path_response'
require 'openapi_client/models/transfer_peer_path_response_all_of'
require 'openapi_client/models/transfer_ticket_response'
require 'openapi_client/models/transfer_ticket_term_response'
require 'openapi_client/models/unfreeze_transaction_response'
require 'openapi_client/models/unmanaged_wallet'
require 'openapi_client/models/unsigned_message'
require 'openapi_client/models/unspent_inputs_data'
require 'openapi_client/models/user_response'
require 'openapi_client/models/validate_address_response'
require 'openapi_client/models/vault_account'
require 'openapi_client/models/vault_asset'
require 'openapi_client/models/vault_wallet_address'
require 'openapi_client/models/wallet_asset'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
